
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace MODEL
{

using System;
    using System.Collections.Generic;
    
public partial class Sys_User
{

    public int UID { get; set; }

    public string UName { get; set; }

    public string UPassword { get; set; }

    public string URealName { get; set; }

    public string UEmail { get; set; }

    public string UTel { get; set; }

    public string Note { get; set; }

    public Nullable<int> IsDel { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

}

}
